### ISSUE TITLE
Error: Error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by gavinpatkinson** [urbit/keygen-js#4]
Branch: `tests`
Encountered when running src/index.js against tests. I think this has to do with argon2wasm.

```Error: Error: connect ECONNREFUSED 127.0.0.1:80
        at Object.dispatchError (/Users/gavinatkinson/Tlon/keygen-js/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
        at Request.client.on.err (/Users/gavinatkinson/Tlon/keygen-js/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:676:20)
        at Request.emit (events.js:187:15)
        at Request.onRequestError (/Users/gavinatkinson/Tlon/keygen-js/node_modules/request/request.js:881:8)
        at ClientRequest.emit (events.js:182:13)
        at Socket.socketErrorListener (_http_client.js:371:9)
        at Socket.emit (events.js:182:13)
        at emitErrorNT (internal/streams/destroy.js:92:8)
        at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
        at process._tickCallback (internal/process/next_tick.js:174:19) undefined
```

**Comment by joemfb** [comment]
fixed by changes to argon2-wasm.

**Comment by gavinpatkinson** [comment]
Hell yeah!
